#!/bin/bash
sudo apt update
sudo apt install wget dialog git -y

CHOICE=$(dialog --clear --title "Chose type of repos to use" \
--backtitle "BASH" --radiolist "Stable or SID?" 11 70 4 \
Stable "Stable debian repos with non-free sofware " "on" \
SID "Testing debian repos woith non-free software" "off" \
--stdout)
echo $CHOICE

if [[ ${CHOICE} == SID ]]
then
	echo "
#------------------------------------------------------------------------------#
#                   OFFICIAL DEBIAN REPOS
#------------------------------------------------------------------------------#
###### Debian Main Repos
deb http://deb.debian.org/debian/ unstable main contrib non-free
deb-src http://deb.debian.org/debian/ unstable main contrib non-free

#------------------------------------------------------------------------------#
#                      UNOFFICIAL  REPOS
#------------------------------------------------------------------------------#

###### 3rd Party Binary Repos
###Steam
deb [arch=i386,amd64] http://repo.steampowered.com/steam/ precise steam
" > /etc/apt/sources.list


MPR(){
	wget -qO - 'https://proget.hunterwittenborn.com/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg &> /dev/null
	echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.hunterwittenborn.com/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
	sudo apt update

}

gpu_detect(){

	GPU=$(lspci | grep -i --color "vga\|3d\|2d")
	if [[ ${GPU} == *NV* ]];
	then
		echo your GPU vendor is NVidia
		sudo apt install -y nvidia-driver
	fi
	
}


games(){
	echo "deb http://download.opensuse.org/repositories/home:/strycore/Debian_10/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
	wget -q https://download.opensuse.org/repositories/home:/strycore/Debian_10/Release.key -O- | sudo apt-key add -
	sudo apt update
	sudo apt install lutris -y
	sudo dpkg --add-architecture i386
	wget -nc https://dl.winehq.org/wine-builds/winehq.key
	sudo apt-key add winehq.key
	rm winehq.key
	sudo apt-get update
	sudo apt-get upgrade -y
	sudo apt-get install --install-recommends winehq-staging wine-staging wine-staging-i386 wine-staging-amd64 -y
	sudo apt-get install --install-recommends winehq-staging -y
	sudo apt-get install libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 libsqlite3-0:i386 -y
	sudo apt install -y steam mesa-vulkan-driver
}

pfetch(){
	git clone https://github.com/dylanaraps/pfetch.git	
	sudo install pfetch/pfetch /usr/local/bin/
	ls -l /usr/local/bin/pfetch
	rm pfetch -rf
}

games
MPR
pfetch

git clone https://mpr.hunterwittenborn.com/yafetch-git.git
cd yafetch-git
makedeb
