#!/bin/bash
BROWSER='firefox'
TERMINAL='kitty'
FM='nemo' #GUI file manager
TFM='ranger' #terminal file manager
COMPOSITOR='picom'
CLIPBOARD_MANAGER='xclip'
OTHER=" numlockx qbittorrent gimp playerctl "
TERMINAL_APPS=" git rar dialog ranger gtop htop vim udisks2 "
GUI_backend="xclip spectacle pulseaudio pavucontrol feh w3m alsa-firmware apulse pulseaudio-alsa alsa-oss nodejs"
GUI=" lxsession nemo xorg polybar lxsession dunst lxappearance yad xdotool"
office_suite=" libreoffice galculator "
multimedia_player="mpv"

function init_detect () {
	PS=$( ps --pid 1 | grep -q systemd && echo 'systemd' || echo 'init' )
	if [[ $PS == *systemd* ]]; 
	then 
		INIT="systemd";
	elif [[ $PS == *init* ]];
	then
		INIT="openrc"
	elif [[ $PS == *runit* ]];
	then
		INIT="runit"

	elif [[ $PS == *s6* ]];
	then
		INIT="s6"
	else 
		INIT="cannot tell"; 
	fi

}

if [[ -f /usr/bin/zypper ]];
then
	sudo zypper --non-interactive install wget dialog curl
elif [[ -f /usr/bin/pacman ]];
then
	sudo pacman -Sy wget dialog curl --noconfirm
elif [[ -f /usr/bin/apt ]];
then
	sudo apt install wget dialog curl -y
fi


CHOICE=$(dialog --clear --title "Okno dialogowe Checklist" --backtitle "BASH" --checklist "Optional support for:" 11 40 4  GNOME "Minimal gnome-shell instalation" "off" dwm "dwm windowm manager by suckless.org" "off" bspwm "bspwm tiling window manager" "off" i3 "i3 tiling window manager" "off" --stdout)

#echo $CHOICE


DISTRO=$(hostnamectl | grep 'Operating System' | awk '{print $3 $4 $5}')
echo "You Are on $DISTRO"
